feat: adding /about command as before
xp-bot/xp-bot pull request #7
Opened 2023-10-30 16:59 UTC by CringleySDays

- Added `/about` command as it was in v7 without any changes

**Notice:** @ConnysCode can you run this code in the host server (using a testing bot) to see if the response time is sent accurately. This depends if the clock is the same as the discord clock. Otherwise it'd return negative results in the 1000s before merging please.

- Error handling is left for future when a proper logging system is in place

2023-10-30 17:01 UTC, ConnysCode commented
@CringleySDays As long as the clock is set correctly, the timezone should not matter. The timestamp is just the time in seconds/milliseconds passed since epoch. This is the same for every timezone.

2023-10-30 17:03 UTC, ConnysCode requested changes

2023-10-30 17:03 UTC, ConnysCode commented on src/commands/info/about.ts
> +  if (!interaction.guildId || !interaction.user.id || !interaction.guild) return;
The command will just time out. Please add a TODO, to hint that the logging system is still missing there.

2023-10-30 17:14 UTC, ConnysCode commented
@CringleySDays Please pull the recent development branch and push that again. <3

2023-10-30 17:15 UTC, ConnysCode approved these changes

2023-10-30 19:10 UTC, ConnysCode commented
Also please add localization. Refer to https://github.com/xp-bot/xp-bot/blob/3d6da0bc362abcc09c5f84104843279110827086/CONTRIBUTING.md?plain=1#L33-L61

2023-10-30 19:49 UTC, CringleySDays commented
Sure, I'll do that once I'm home

2023-10-31 09:16 UTC, CringleySDays commented
I'm not sure if this is how you want me to do it, I think I did it. I'm not too sure sorry

2023-10-31 09:17 UTC, ConnysCode requested changes

2023-10-31 09:17 UTC, ConnysCode commented on src/commands/info/about.ts
> +          'Elevate your Community to the next Level with Top-Tier Leveling, endless Customisability and more.',
Every string needs to be localised.

2023-10-31 09:18 UTC, CringleySDays commented
The way I did it for footer is correct right?

2023-10-31 10:05 UTC, ConnysCode requested changes

2023-10-31 10:05 UTC, ConnysCode commented on src/commands/info/about.ts
> +        name: t('fields.summary_title', {
Where are these localisations supposed to come from? You gotta define them in the `/locales/{{lng}}/{{namespace}}.json` files.

2023-10-31 11:46 UTC, ConnysCode requested changes

2023-10-31 11:46 UTC, ConnysCode commented on src/locales/en/about_command.json
> +  "fields": {
categories are meant to be in a singular wording.

```diff
+ field
- fields
```

2023-10-31 11:46 UTC, ConnysCode commented on src/locales/en/about_command.json
> +    "fields.server_support_link": "[Join XP]({{link}})",
duplicated category "fields" in key.

2023-10-31 11:46 UTC, ConnysCode commented on src/locales/en/about_command.json
> +    "response_shard_company_info": "Response time: {{response}}ms • Shard: {{shard}} • © {{company}}"
These symbols are a headache to translate.
Please split them individual keys.
F.e. `response_time_n`, `shard_n`, ...

2023-10-31 11:46 UTC, ConnysCode commented on src/commands/info/about.ts
> +    .setTitle(`${t('title.title', { lng: 'en', ns: 'about_command' })}}`)
why is the title in the title category?

just key `title`, no category needed.

2023-10-31 12:07 UTC, CringleySDays commented
I removed the symbols and replaced it with commas

2023-10-31 12:08 UTC, ConnysCode commented
> I removed the symbols and replaced it with commas

No, the about command is to be the exact same as it is now. The symbols need to stay, just not as part of the translation string.

2023-10-31 12:11 UTC, ConnysCode requested changes

2023-10-31 12:11 UTC, ConnysCode commented on src/commands/info/about.ts
>            //'[Join XP](https://discord.com/invite/ccTAnzw)'
The links should be part of the translation! Only the "Join XP" should be translatable. Why would we translate a discord.com link?

2023-10-31 12:11 UTC, ConnysCode commented on src/locales/en/about_command.json
> +    "company_n": "by {{company}}"
`by_company`.

`n` is a placeholder hinting to a number. Strings are to be expected to be interpolated. Numbers potentially follow different logics.

2023-10-31 12:13 UTC, ConnysCode commented on src/locales/en/about_command.json
> +    "title": "Reimagine your Community"
Now that i think of it, this should also not be translated, due to this being our slogan. Slogans do not get translated.

2023-11-01 17:33 UTC, CringleySDays commented
I think I did it as you told me to, I'm not too sure 😅

2023-11-01 17:56 UTC, ConnysCode requested changes

2023-11-01 17:56 UTC, ConnysCode commented on src/commands/info/about.ts
>            //'[Join XP](https://discord.com/invite/ccTAnzw)'
Idk but this is still not correct.

Only "Join XP" should be localized.

2023-11-01 17:56 UTC, ConnysCode commented on src/commands/info/about.ts
> +        value: t('field.status_link', {
Here as well, only "Status" should be localized.

2023-11-01 17:56 UTC, ConnysCode commented on src/commands/info/about.ts
> +    console.error(error);
BTW error system has been implemented. Please throw a "new XPError" wherever code could fail.

2023-11-01 17:56 UTC, ConnysCode commented on src/commands/info/about.ts
> +    .setLabel('Server Dashboard')
These buttons also have not been localized.

2023-11-01 18:41 UTC, ConnysCode requested changes

2023-11-01 18:41 UTC, ConnysCode commented on src/commands/info/about.ts
>            //'[Join XP](https://discord.com/invite/ccTAnzw)'
??

2023-11-01 18:41 UTC, ConnysCode commented on src/commands/info/about.ts
>            //'[Join XP](https://discord.com/invite/ccTAnzw)'
```ts
value: `[${t('field.server_link'), {...}}](https://discord.com/invite/ccTAnzw)`
```

2023-11-01 20:15 UTC, ConnysCode requested changes

2023-11-01 20:15 UTC, ConnysCode commented on src/commands/info/about.ts
>      await interaction.reply({
Don't reply when throwing an XPError. The error handler does that for you.

2023-11-01 20:15 UTC, ConnysCode commented on src/commands/info/about.ts
> +    throw new XPError(XPErrorType.INTERACTION_GUILD_UNRESOLVABLE);
This error is only for not being able to resolve a guild. Please add a separate condition for not being able to resolve the user id.

2023-11-01 20:15 UTC, ConnysCode commented on src/commands/info/about.ts
> +    throw new XPError(XPErrorType.INTERACTION_GUILD_UNRESOLVABLE);
But thats not what's happening here.

2023-11-07 15:14 UTC, ConnysCode requested changes

2023-11-07 15:14 UTC, ConnysCode commented on src/commands/info/about.ts
> +  if (!interaction.guildId || !interaction.guild) {
We don't use the interaction.guild, so we don't have to check for it.

2023-11-07 15:14 UTC, ConnysCode commented on src/commands/info/about.ts
> +        name: t('field.summary_title', {
`field.summary.title`

2023-11-07 15:14 UTC, ConnysCode commented on src/commands/info/about.ts
> +        value: t('field.summary_description', {
`field.summary.description`

2023-11-07 15:14 UTC, ConnysCode commented on src/commands/info/about.ts
> +        name: t('field.server_title', {
See comments above.

2023-11-07 15:14 UTC, ConnysCode commented on src/commands/info/about.ts
> +            shard: interaction.guild.shardId + 1,
`discordClient.shard?.ids[0]`

2023-11-07 15:14 UTC, ConnysCode commented on src/commands/info/about.ts
> +    throw new XPError(XPErrorType.INTERACTION_USER_UNRESOLVABLE);
how is that an accurate description for what failed here?

2023-11-07 15:14 UTC, ConnysCode commented on yarn.lock
> +<<<<<<< HEAD
Merge annotations.

2023-11-07 15:14 UTC, ConnysCode commented on CONTRIBUTING.md
> +<<<<<<< HEAD
Merge annotations.

2023-11-17 23:34 UTC, closed without merging